version: "3"
services:
  latex:
    env_file: .env
    environment:
      HOME: /home/dev
    build:
      context: .
      args:
        USER_NAME: dev
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    tty: true
    volumes:
      - type: bind
        source: ../workdir
        target: /home/dev/workdir
      - type: bind
        source: ~/.ssh
        target: /home/dev/.ssh
        read_only: true
      - type: bind
        source: ~/.config
        target: /home/dev/.config
        read_only: true
